"""
This script is written based on python3 which tells the average depth of the sample sequenced on Illumina or MGI or Nanopore
The input for this script is the output generated by the samtools command given below
samtools depth -a -d 20000 sample.bam -o sample_coverage.txt

Sample of how the sample_coverage.txt (tab delimited) file generated by samtools look like excluding the header
chrName Pos No.of reads
chr1	1	0
chr1	2	0
chr1	3	0
chr1	4	0
"""

import pandas as pd
import numpy as np
import os

pwd = os.getcwd()
list = os.listdir()
print("\nYour current working directory (CWD) is",pwd)
print("\nThese are the list of contents in your CWD, Choose the appropriate one or give the full path of the file to be processed :D \n","\n", list)
print("\nThe coverage file should not contain any header")
file = input("\nGive the path of the coverage file \t:\t") ## Give the file path here, it should not contain any headder
df = pd.read_csv(file, sep="\t")
np_df = np.array(df)
np_cov_sum = sum(np_df[:,2])
np_cov_count = len(np_df[:,2])
avg_coverage = np_cov_sum/np_cov_count

print("\n" "The average/mean coverage of the sample is",str(avg_coverage) + "x")
print("\nThe rounded average/mean coverage of the sample is",str(round(avg_coverage)) + "x")